### ISSUE TITLE
代码清单2-10中删除所有排名在20 000名之后的商品这句代码有误

### ISSUE THREAD

**Issue by jiangbuyuuxs** [huangz1990/ria-cn-website#1]
删除所有排名在20 000名之后的商品。
conn.zremrangebyrank('viewed:', 0, -20001)
这样的写法删除的是排名前20000的商品.

**Comment by huangzworks** [comment]
谢谢反馈，代码是正确的。

注意代码中的下标为 ``-20001`` 而不是 ``20001`` ，这个调用的效果其实跟 ``conn.zremrangebyrank('viewed:', 20000, -1)`` 是一样的。

个人觉得作者这里选择的这种写法很不好，很容易引起人误会，已经有好几个读者向我反馈这个问题了。

**Comment by jiangbuyuuxs** [comment]
!
这是因为python库里面做的处理么.

因为zremrangebyrank命令好像是没有这种功能的吧.

有些怀疑你拿到的书稿不是最终稿.因为英文版上面就是第二种写法.`conn.zremrangebyrank('viewed:', 20000, -1)`

**Comment by huangzworks** [comment]
在对照了原版的纸质书和电子书之后，发现原文的确就是第二种写法。

译本中的写法实际上出自源码文件： https://github.com/huangz1990/riacn-code/blob/master/ch02_listing_source.py#L183

可能是我在翻译的过程中用源码文件里面的代码覆盖了原书的代码，所以才出现了这样的问题，给你造成困惑了，不好意思。

这两种写法都会产生相同的效果，但第二种写法无疑更易懂一些，我已经把这个错误记录到出版社的勘误里面了，书本下次重印就会做修正，感谢你的反馈！
